# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# gem "github-pages", group: :jekyll_plugins
# title: My Website
# description: Welcome to my website!
# show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
remote_theme: jekyll-theme-cayman
header_pages:
  - Home: /
  - About: /about
sidebar:
  title: Welcome!
  nav:
    - Getting Started: /getting-started/
    - Blog: /blog/
    - Contact: /contact/
social_links:
  github: jiangzs
  twitter: jiangzs
  linkedin: jiangzs
sass:
  style: compressed
github_pages:
  publish: true
  jekyll_version: 3.9.0